include $(TOPDIR)/rules.mk

LUCI_TITLE:=Firmware Updater
LUCI_DEPENDS:=+luci-base +rpcd-mod-luci +wget
PKG_MAINTAINER:=DaBoiCJ <daboicj@softmodd.ing>
PKG_LICENSE:=GPL-3.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
